# Generated by Django 5.2.15 on 2026-07-11 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес (slug)')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Картинка')),
                ('teaser', models.TextField(blank=True, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('published', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published'],
            },
        ),
    ]
