# Generated by Django 6.0.5 on 2026-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Подукты'},
        ),
        migrations.AddField(
            model_name='part',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем левее карточка', verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем левее карточка', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, upload_to='parts/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
